index:
    path: /
    controller: App\Controller\HomepageController::index

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
